default:
  image: gradle:7.5.1
  tags:
    - shared

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - docker
  - deploy

build-job:    
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar

unit-test-job:
  stage: test
  script:
    - gradle check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

docker-job:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."