stages:
  - build
  - test
  - docker
  - deploy

build-job:    
  image: gradle:7.5.1
  stage: build
  script:
    - gradle assemble
  tags:
    - shared

unit-test-job:
  image: gradle:7.5.1
  stage: test
  script:
    - gradle check
  tags:
    - shared

docker-job:
  image: docker:20.10.21
  stage: docker
  script:
    - docker build .
  tags:
    - shared

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - shared
