default:
  image: gradle:7.5.1
  tags:
    - shared

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - publish
  - deploy

#build-job:
#  stage: build
#  script:
#    - gradle assemble
#  artifacts:
#    paths:
#      - build/libs/*.jar
#
#unit-test-job:
#  stage: test
#  script:
#    - gradle check
#  artifacts:
#    when: always
#    reports:
#      junit: build/test-results/test/**/TEST-*.xml
#
#publish:
#  stage: publish
#  image:
#    name: gcr.io/kaniko-project/executor:v1.9.0-debug
#    entrypoint: [""]
#  script:
#    - /kaniko/executor
#      --context "${CI_PROJECT_DIR}"
#      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
#      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

deploy:
  stage: deploy
  when: manual
  only:
    - "main"
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_IP_PUBLIC >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "docker-compose -f ~/app/docker-compose.yml down --rmi local --remove-orphans"
    - echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
    - echo PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD >> .env
    - echo KEYCLOAK_URL=$KEYCLOAK_URL >> .env
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "mkdir -p ~/app"
    - scp -r docker-compose.yml ubuntu@${SERVER_IP_PUBLIC}:~/app
    - scp -r .env ubuntu@${SERVER_IP_PUBLIC}:~/app
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USER --password-stdin $REGISTRY_URL"
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "docker image rm registry.inovex.de:4567/railabouni/inoventory-service"
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "docker-compose -f ~/app/docker-compose.yml up -d"
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "rm -f ~/app/.env" # For some reason unable to run SSH in after_script
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "docker logout"
  after_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-keyscan -H $SERVER_IP_PUBLIC >> ~/.ssh/known_hosts
    - ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP_PUBLIC "rm -f ~/app/.env"
