image: gradle:7.5.1

services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
      
variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - docker
  - deploy

build-job:    
  stage: build
  script:
    - gradle assemble
  tags:
    - shared
  artifacts:
    paths:
      - /build/libs/*.jar

unit-test-job:
  stage: test
  script:
    - gradle check
  tags:
    - shared

docker-job:
  image: docker:latest
  stage: docker
  script:
    - ls /build/libs/
    - docker build .
  tags:
    - shared

    

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  tags:
    - shared
