services:
  app:
    image: ghcr.io/inoventory-org/inoventory-service:${APP_TAG}
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=/run/secrets/postgres_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KEYCLOAK_URL=/run/secrets/keycloak_url
    ports:
      - "8080:8080"
    networks:
      - inoventory
  db:
    image: postgres
    container_name: postgres_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - inoventory
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/pgadmin_default_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - inoventory
    restart: unless-stopped

networks:
  inoventory:
    driver: bridge

volumes:
  postgres:
  pgadmin:

secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
  pgadmin_default_password:
    environment: PGADMIN_DEFAULT_PASSWORD
  keycloak_url:
    environment: keycloak_url

