services:
  backend:
    # === REMOTE IMAGE ===
    # Comment this out if you want to use the local build below
    image: ghcr.io/inoventory-org/inoventory-service:${APP_TAG:-latest}
    
    # === LOCAL BUILD ===
    # Uncomment the following block to build from your local Dockerfile
    #build:
    #  context: .
     # dockerfile: Dockerfile
    
    container_name: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - inoventory
      

networks:
  inoventory:
    driver: bridge

volumes:
  postgres:
