spring.datasource.url=postgresql://db.tncuiwvsvyixivsfhpqv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=dHr7Awit8&bTE9V
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=DEBUG

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true
server.error.include-message=always
server.error.include-stacktrace=on_param

cors.originPatterns=*

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tncuiwvsvyixivsfhpqv.supabase.co/auth/v1
supabase.jwt.audience=authenticated
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES=true

openfoodfacts.baseurl="https://de.openfoodfacts.net"

product.cache.ttl=5m
product.cache.max-size=100
